### ISSUE TITLE
Need to test that bad queries raise expected errors

### ISSUE THREAD

**Issue by SohierDane** [SohierDane/BigQuery_Helper#8]
Queries with bad syntax may register as `bq_helper` errors rather than raising the underlying exception. Need to test a bad query and ensure that it raises the correct error.

**Comment by LeData** [comment]
I was actually looking at this today. I might make a pull request soon.

**Comment by LeData** [comment]
Well, I was going to make the query return the error messages, but it is actually simpler to do like you did. Just let the error be raised.

**Comment by SohierDane** [comment]
@LeData I like that my solution is simple, but it's not very explicit without the lengthy code comment. 
I also feel weird calling a method on an error message.

I'd love to see a PR with more explicit handling of the exception if you have something in mind.

**Comment by LeData** [comment]
@SohierDane , I'm no Software engineer though... I was going to simply write an if/else statement checking if the status dictionary of the client had a  error key and then either raise the error message or return the results. As it turns out your workaround lets the client raise the error itself, so I felt the job was done.

**Comment by SohierDane** [comment]
That makes sense. I'll leave that as is then, and this thread open as I still need to write a test for this case.
